name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
permissions:
  checks: write
  pull-requests: write
jobs:
  ci:
    uses: HeyItsGilbert/.github/workflows/ModuleCI.yaml@latest
